In [2]:
import pandas as pd

In [3]:
data = pd.read_excel(r"C:\Users\VitoriaRodrigues\Documents\Desafio\ETL\arquivos Pythom\BaseTargetListv.xlsx")
data.loc[:, 'BuyerSubPk'] = data['Buyer'] + data['BuyerSubSector']

data

,Buyer,BuyerSubSector,Client,ClientSubSector,BuyerContact,LastContactDate,PassedReason,SignedNDADate,SubmittedNBODate,EstimatedDealSize,Deal Close Date,BuyerSubPk
0,Grupo Gps,Logistica,E-Vertical 2021,"Serviços Terceirizados (limpeza, segurança e c...",NaN,2021-08-02,NaN,NaT,2021-08-02,NaN,2022-06-24,Grupo GpsLogistica
1,Advent,Asset Management,Absolute Investimentos,Asset Management,PDonato@adventinternational.com.br,2021-08-02,Too Big,NaT,NaT,600.0,2022-06-23,AdventAsset Management
2,Nubank,Fintech,Absolute Investimentos,Asset Management,paulo.barbosa@nubank.com.br,2021-08-09,Timing,NaT,NaT,600.0,2022-06-23,NubankFintech
3,Pagseguro,Meios de Pagamento,Absolute Investimentos,Asset Management,mlcruz@pagseguro.com,2021-09-23,Too Big,NaT,NaT,600.0,2022-06-23,PagseguroMeios de Pagamento
4,Mercado Livre,Marketplace Diversos,Absolute Investimentos,Asset Management,NaN,2021-08-10,Not an Industry Focus,NaT,NaT,600.0,2022-06-23,Mercado LivreMarketplace Diversos
...,...,...,...,...,...,...,...,...,...,...,...,...
12923,Swimwear Anywhere,Varejo Especializado,Triya Beachwear,Varejo Especializado,NaN,2022-07-25,NaN,NaT,NaT,80.0,NaT,Swimwear AnywhereVarejo Especializado
12924,Grupo Inditex,NaN,Triya Beachwear,Varejo Especializado,NaN,2022-07-25,NaN,NaT,NaT,80.0,NaT,NaN
12925,Inspecs,Varejo Especializado,Triya Beachwear,Varejo Especializado,NaN,2022-07-25,NaN,NaT,NaT,80.0,NaT,InspecsVarejo Especializado
12926,Digital House,Edtech,K21,IT Services,NaN,2022-07-25,NaN,NaT,NaT,100.0,NaT,Digital HouseEdtech
12927,Sputnik,Edtech,K21,IT Services,NaN,2022-07-25,NaN,NaT,NaT,100.0,NaT,SputnikEdtech

### Número de vezes em que esse buyer foi considerado para deals neste sub-setor;

In [4]:
df_buyers = pd.DataFrame(data) 

df_buyers= data[data['Deal Close Date'].notna()]

df_buyers.loc[:, 'BuyerSubPk'] = df_buyers['Buyer'] + df_buyers['BuyerSubSector']
df_buyers = df_buyers.groupby(['BuyerSubPk'])['Deal Close Date'].count().reset_index()

df_buyers

                                            BuyerSubPk  Deal Close Date
0                          220 CapitalAsset Management                2
1          3g CapitalWealth & Capital Markets Tech OLD                1
2                        ACE & CompanyAsset Management                1
3    ADDviseDental & Medical devices (produção e di...                1
4    ADPServiços Terceirizados (limpeza, segurança ...                2
..                                                 ...              ...
832                            ZohoSaaS - Generalistas                1
833        ZucchettiERP (Enterprise Resource Planning)                2
834  Zurich SegurosSeguradoras & Corretoras de Seguros                1
835                        sprinklrSaaS - Generalistas                1
836                   stagwell groupMarketing Services                2

[837 rows x 2 columns]

### Número de NDAs assinados por esse buyer para deals neste sub-setor;

In [5]:
df_buyers = pd.DataFrame(data) 

df_buyers.loc[:, 'BuyerSubPk'] = df_buyers['Buyer'] + '-' + df_buyers['BuyerSubSector']
df_buyers = df_buyers.groupby(['BuyerSubPk'])['SignedNDADate'].count().reset_index()

df_buyers

                                             BuyerSubPk  SignedNDADate
0                    123 Milhas-Turismo, Entretenimento              0
1      180° Seguros-Seguradoras & Corretoras de Seguros              0
2                          220 Capital-Asset Management              1
3               2M Holdings-Supermercados e Atacadistas              0
4     3 Corações-Mercearia Seca, Condimentos e Produ...              2
...                                                 ...            ...
4088                         xoxoday-Marketing Services              0
4089  zeppelin-Indústria Pesada, Máquinas e Equipame...              0
4090                      ziff davis-Marketing Services              0
4091   Água Da Serra Industrial De Bebidas Ltda-Bebidas              0
4092                             Órama-Asset Management              0

[4093 rows x 2 columns]

###	Número de No Gos do buyer neste sub-setor;

In [7]:
df_buyers = pd.DataFrame(data) 

df_buyers.loc[:, 'BuyerSubPk'] = df_buyers['Buyer'] + '-' + df_buyers['BuyerSubSector']
df_buyers = df_buyers.groupby(['BuyerSubPk'])['PassedReason'].count().reset_index()

df_buyers

                                             BuyerSubPk  PassedReason
0                    123 Milhas-Turismo, Entretenimento             0
1      180° Seguros-Seguradoras & Corretoras de Seguros             1
2                          220 Capital-Asset Management             2
3               2M Holdings-Supermercados e Atacadistas             0
4     3 Corações-Mercearia Seca, Condimentos e Produ...             1
...                                                 ...           ...
4088                         xoxoday-Marketing Services             0
4089  zeppelin-Indústria Pesada, Máquinas e Equipame...             1
4090                      ziff davis-Marketing Services             0
4091   Água Da Serra Industrial De Bebidas Ltda-Bebidas             0
4092                             Órama-Asset Management             0

[4093 rows x 2 columns]

### Número de No Gos, por razão de tamanho, neste sub-setor;

In [8]:
df_buyerf = pd.DataFrame(data)
df_buyerf = df_buyerf.groupby(['BuyerSubPk'])['PassedReason'].sum().reset_index()

df_size = df_buyerf['PassedReason'].isin(['Too Small', 'Too Big'])
df_filterd = df_buyerf[df_size]

df_filterd

                                             BuyerSubPk PassedReason
44    ARTDECO Cosmetic-Produtos de Uso Pessoal e Cos...    Too Small
108                                   Aes Tietê-Energia      Too Big
142   Alcast-Materiais Básicos e Produtos para Const...      Too Big
178          Alpha Imaging, LLC-Análises e Diagnósticos      Too Big
198   Alvo Medical-Dental & Medical devices (produçã...    Too Small
...                                                 ...          ...
3815              Valora Investimentos-Asset Management    Too Small
3934                      Webfones-Varejo Especializado      Too Big
3937                         Weidmuller Holding-Energia      Too Big
4003                      YAYA Capital-Asset Management      Too Big
4051                             Zynga-SaaS - Setoriais    Too Small

[97 rows x 2 columns]

### Número de NBOs enviadas pelo buyer para deals neste sub-setor;

In [9]:
df_client= pd.DataFrame(data) 

df_client = df_client.groupby(['ClientSubSector'])['SubmittedNBODate'].count().reset_index()
df_client

                                      ClientSubSector  SubmittedNBODate
0                 Agricultura de precisão/implementos                 1
1                                Agricultura/Produção                 0
2                             Análises e Diagnósticos                 1
3                                    Asset Management                13
4                                     Açucar e Álcool                 0
5                                 Bancos Tradicionais                 0
6                                             Bebidas                 3
7         Clínicas, Hospitais e Centros de Tratamento                 3
8                                          Consulting                 3
9           Deathcare (Cemitério e Planos funerários)                 1
10  Dental & Medical devices (produção e distribui...                12
11                                  Distribuição Agro                26
12                            Distribuição industrial                13
13                                             Edtech                 0
14                                           Educação                 4
15                                         Embalagens                 2
16                                            Energia                 6
17                                      Ensino Básico                10
18                                    Ensino Superior                 6
19                         Fertilizantes & Defensivos                20
20  Fertilizantes, especiais, químicos e sementes OLD                 1
21                                            Fintech                12
22                         Frutas, Legumes e Verduras                 5
23                  Geração de conteúdo e Publicações                 6
24                       Gestão de residuos e aterros                 0
25                                          Hotelaria                 1
26                                        IT Services                56
27  Industria e distribuição de Químicos & Ingredi...                13
28                               Indústria Automotiva                 3
29                             Indústria Farmacêutica                 7
30          Indústria Pesada, Máquinas e Equipamentos                 5
31                          Infraestrutura de Telecom                 3
32                                          Insurtech                 0
33                                     Laje Comercial                 0
34                                  Locação de Ativos                 2
35                                          Logistica                 5
36                   Lácteos, sorvetes e refrigerados                 1
37                                 Marketing Services                 4
38                               Marketplace Diversos                 5
39  Materiais Básicos e Produtos para Construção (...                 8
40                                 Meios de Pagamento                 4
41   Mercearia Seca, Condimentos e Produtos Saudáveis                 3
42                                       Multi-family                 1
43                                    Nutrição animal                 1
44                           Pet (Indústria e Varejo)                 0
45                                Produtos de Limpeza                 0
46               Produtos de Uso Pessoal e Cosméticos                 9
47                                    Residencial OLD                 1
48                            Restaurantes & Delivery                 0
49                                       Saúde animal                 2
50                Seguradoras & Corretoras de Seguros                 4
51  Serviços Terceirizados (limpeza, segurança e c...                11
52                       Serviços de Engenharia e TIC                 9
53                                           Software                29
54                                Soluções de Crédito                 0
55                        Supermercados e Atacadistas                 0
56                               Varejo Especializado                12

### Média do tamanho dos deals (considerando apenas deals com NDA assinado por esse buyer) para deals neste sub-setor;

In [29]:
df_buyers = pd.DataFrame(data)
pd.options.display.float_format = '{:.0f}'.format

df_buyers = df_buyers[df_buyers['EstimatedDealSize'].notnull()]   
deals_nda = df_buyers[df_buyers['SignedNDADate'].notnull()]

mean_size_deals= deals_nda.groupby('BuyerSubPk')['EstimatedDealSize'].mean().reset_index()

mean_size_deals

                                            BuyerSubPk  EstimatedDealSize
0    3 Corações-Mercearia Seca, Condimentos e Produ...                150
1    3D Systems-Indústria Pesada, Máquinas e Equipa...                100
2    AAK-Industria e distribuição de Químicos & Ing...                138
3                         ARC Capital-Asset Management                400
4                                 ATkearney-Consulting                150
..                                                 ...                ...
423                                     Yduqs-Educação                 90
424              You Inc.-Serviços de Engenharia e TIC                120
425                               Zenitech-IT Services                200
426  iFood-Serviços Terceirizados (limpeza, seguran...                167
427                  stagwell group-Marketing Services                150

[428 rows x 2 columns]


### Mediana do tamanho do deal (considerando apenas deals com NDA assinado por esse buyer) para deals neste sub-setor

In [30]:
df_buyers = pd.DataFrame(data)
pd.options.display.float_format = '{:.0f}'.format

df_buyers = df_buyers[df_buyers['EstimatedDealSize'].notnull()]   
deals_nda = df_buyers[df_buyers['SignedNDADate'].notnull()]

media_size_deals= deals_nda.groupby('BuyerSubPk')['EstimatedDealSize'].median().reset_index()

media_size_deals

                                            BuyerSubPk  EstimatedDealSize
0    3 Corações-Mercearia Seca, Condimentos e Produ...                150
1    3D Systems-Indústria Pesada, Máquinas e Equipa...                100
2    AAK-Industria e distribuição de Químicos & Ing...                138
3                         ARC Capital-Asset Management                400
4                                 ATkearney-Consulting                150
..                                                 ...                ...
423                                     Yduqs-Educação                 90
424              You Inc.-Serviços de Engenharia e TIC                120
425                               Zenitech-IT Services                200
426  iFood-Serviços Terceirizados (limpeza, seguran...                150
427                  stagwell group-Marketing Services                150

[428 rows x 2 columns]

### Data da última NBO enviada pelo buyer para deals neste sub-setor;

In [31]:
df_buyers = df_buyers.groupby(['SubmittedNBODate'])['ClientSubSector'].sum().reset_index()
df_buyers

       SubmittedNBODate                                    ClientSubSector
0   2020-05-22 14:56:00          Indústria Pesada, Máquinas e Equipamentos
1   2020-06-11 16:37:00                                 LogisticaLogistica
2   2020-06-22 00:00:00                                           Software
3   2020-06-25 00:00:00                                           Software
4   2020-07-05 00:00:00                                           Software
..                  ...                                                ...
154 2022-07-15 19:36:00                                        IT Services
155 2022-07-18 09:37:00                               Varejo Especializado
156 2022-07-18 09:46:00  Industria e distribuição de Químicos & Ingredi...
157 2022-07-21 18:11:00                                 Meios de Pagamento
158 2022-07-25 18:41:00                                        IT Services

[159 rows x 2 columns]

### Número de deals fechados por esse buyer neste sub-setor;

In [32]:
df_client = pd.DataFrame(data) 
df_client= data[data['Deal Close Date'].notna()]

df_client = df_client.groupby(['Deal Close Date'])['ClientSubSector'].max().reset_index()
df_client

   Deal Close Date                                    ClientSubSector
0       2019-06-19                                        IT Services
1       2020-10-30                                          Logistica
2       2020-11-03                                           Educação
3       2020-11-30                            Distribuição industrial
4       2020-12-15               Produtos de Uso Pessoal e Cosméticos
5       2020-12-21                                        IT Services
6       2020-12-22                                           Software
7       2021-02-12                                        IT Services
8       2021-02-26  Industria e distribuição de Químicos & Ingredi...
9       2021-03-18                                            Fintech
10      2021-03-23  Fertilizantes, especiais, químicos e sementes OLD
11      2021-03-31                                  Distribuição Agro
12      2021-04-08                                        IT Services
13      2021-05-06          Indústria Pesada, Máquinas e Equipamentos
14      2021-05-07                                        IT Services
15      2021-05-26                                 Marketing Services
16      2021-07-01                                    Ensino Superior
17      2021-07-02                               Marketplace Diversos
18      2021-08-09                                   Asset Management
19      2021-08-31                                           Software
20      2021-09-01  Serviços Terceirizados (limpeza, segurança e c...
21      2021-09-03                                  Distribuição Agro
22      2021-09-21                                            Bebidas
23      2021-10-01                       Serviços de Engenharia e TIC
24      2021-10-05                                           Software
25      2021-10-15               Produtos de Uso Pessoal e Cosméticos
26      2021-11-01                         Fertilizantes & Defensivos
27      2021-11-04                                             Edtech
28      2021-11-12                                   Asset Management
29      2021-12-01  Industria e distribuição de Químicos & Ingredi...
30      2021-12-10                            Distribuição industrial
31      2022-01-04                  Geração de conteúdo e Publicações
32      2022-01-17                                        IT Services
33      2022-02-03                         Fertilizantes & Defensivos
34      2022-02-11                                        IT Services
35      2022-02-16                                  Distribuição Agro
36      2022-02-25                               Varejo Especializado
37      2022-03-31                                         Consulting
38      2022-04-04                                           Software
39      2022-04-14                                 Meios de Pagamento
40      2022-04-27                       Serviços de Engenharia e TIC
41      2022-06-03  Dental & Medical devices (produção e distribui...
42      2022-06-23                                   Asset Management
43      2022-06-24  Serviços Terceirizados (limpeza, segurança e c...

### Data do último deal fechado neste sub-setor;

In [33]:
df_clients = pd.DataFrame(data)

df_clients = df_clients.groupby(['Deal Close Date'])['ClientSubSector'].max().reset_index()
df_clients

   Deal Close Date                                    ClientSubSector
0       2019-06-19                                        IT Services
1       2020-10-30                                          Logistica
2       2020-11-03                                           Educação
3       2020-11-30                            Distribuição industrial
4       2020-12-15               Produtos de Uso Pessoal e Cosméticos
5       2020-12-21                                        IT Services
6       2020-12-22                                           Software
7       2021-02-12                                        IT Services
8       2021-02-26  Industria e distribuição de Químicos & Ingredi...
9       2021-03-18                                            Fintech
10      2021-03-23  Fertilizantes, especiais, químicos e sementes OLD
11      2021-03-31                                  Distribuição Agro
12      2021-04-08                                        IT Services
13      2021-05-06          Indústria Pesada, Máquinas e Equipamentos
14      2021-05-07                                        IT Services
15      2021-05-26                                 Marketing Services
16      2021-07-01                                    Ensino Superior
17      2021-07-02                               Marketplace Diversos
18      2021-08-09                                   Asset Management
19      2021-08-31                                           Software
20      2021-09-01  Serviços Terceirizados (limpeza, segurança e c...
21      2021-09-03                                  Distribuição Agro
22      2021-09-21                                            Bebidas
23      2021-10-01                       Serviços de Engenharia e TIC
24      2021-10-05                                           Software
25      2021-10-15               Produtos de Uso Pessoal e Cosméticos
26      2021-11-01                         Fertilizantes & Defensivos
27      2021-11-04                                             Edtech
28      2021-11-12                                   Asset Management
29      2021-12-01  Industria e distribuição de Químicos & Ingredi...
30      2021-12-10                            Distribuição industrial
31      2022-01-04                  Geração de conteúdo e Publicações
32      2022-01-17                                        IT Services
33      2022-02-03                         Fertilizantes & Defensivos
34      2022-02-11                                        IT Services
35      2022-02-16                                  Distribuição Agro
36      2022-02-25                               Varejo Especializado
37      2022-03-31                                         Consulting
38      2022-04-04                                           Software
39      2022-04-14                                 Meios de Pagamento
40      2022-04-27                       Serviços de Engenharia e TIC
41      2022-06-03  Dental & Medical devices (produção e distribui...
42      2022-06-23                                   Asset Management
43      2022-06-24  Serviços Terceirizados (limpeza, segurança e c...

### Contato do buyer, considerando a data de contato mais recente;

In [34]:
df_buyer_sub = pd.DataFrame(data)

df_buyer_sub = df_buyer_sub.astype({'Client': str, 'Buyer': str})
df_buyer_sub = df_buyer_sub.groupby('LastContactDate').agg({'Client': lambda x: ', '.join(x.unique()), 'Buyer': lambda x: ', '.join(x.unique())}).reset_index()

df_buyer_sub['LastContactDate'].iloc[-1]
df_buyer_sub

,LastContactDate,Client,Buyer
0,2019-06-07,Sweet Fruits,HIG Capital
1,2019-08-10,Pollux,GROB-WERKE
2,2019-08-14,Pollux,Omron Automation Americas
3,2019-08-21,Pollux,Southern Cross
4,2019-09-10,Pollux,"Precision Castparts Corp., Mondragon Assembly"
...,...,...,...
695,2022-07-26,"Framework, Pixit, BSC Químicos, De Bev, Sabora...","Intive, stagwell group, IMCD, Manuchar, Ambev,..."
696,2022-07-27,"Zbra, Bionatus 2022, Pixit","Concentrix, Hypera Pharma, Hcl"
697,2022-07-28,"Pixit, Vitao Alimentos","Deloitte, Principia"
698,2022-07-29,"Interação Resíduos, Prime Energy","Veolia, Shell International Petroleum Company ..."
699,2022-08-01,Zbra,Mckinsey&company

### Booleano indicando se o sub-setor em questão é o mesmo sub-setor do buyer.

In [41]:
df_sector = pd.DataFrame(data)
df_sector_selected = df_sector[['Buyer', 'Client', 'BuyerSubSector', 'ClientSubSector']]]

df_sector_selected = df_sector_selected.copy()
df_sector_selected['SameSubSector'] = df_sector_selected['BuyerSubSector'] == df_sector_selected['ClientSubSector']
#df_sector_selected.loc[:, 'SameSubSector'] = df_sector_selected['BuyerSubSector'] == df_sector_selected['ClientSubSector']

df_sector_selected

,Buyer,Client,BuyerSubSector,ClientSubSector,SameSubSector
0,Grupo Gps,E-Vertical 2021,Logistica,"Serviços Terceirizados (limpeza, segurança e c...",False
1,Advent,Absolute Investimentos,Asset Management,Asset Management,True
2,Nubank,Absolute Investimentos,Fintech,Asset Management,False
3,Pagseguro,Absolute Investimentos,Meios de Pagamento,Asset Management,False
4,Mercado Livre,Absolute Investimentos,Marketplace Diversos,Asset Management,False
...,...,...,...,...,...
12923,Swimwear Anywhere,Triya Beachwear,Varejo Especializado,Varejo Especializado,True
12924,Grupo Inditex,Triya Beachwear,NaN,Varejo Especializado,False
12925,Inspecs,Triya Beachwear,Varejo Especializado,Varejo Especializado,True
12926,Digital House,K21,Edtech,IT Services,False
12927,Sputnik,K21,Edtech,IT Services,False